name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  security-events: write
  actions: read

jobs:
  gitleaks:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  semgrep:
    name: SAST - Semgrep
    runs-on: ubuntu-latest
  
    container:
      image: semgrep/semgrep
  
    steps:
      - uses: actions/checkout@v4
  
      - name: Run Semgrep scan
        run: |
          semgrep scan \
            --config p/security-audit \
            --config p/secrets \
            --sarif \
            --output semgrep-results.sarif .
  
      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: semgrep-results.sarif
          category: semgrep
          
  trivy:
    name: Container Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t devops-demo-app:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: 'devops-demo-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'


  sonarqube:
    name: SonarQube Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   #    - name: Debug Sonar Task
   #     run: cat .scannerwork/report-task.txt
   #   - name: SonarQube Quality Gate
   #     uses: sonarsource/sonarqube-quality-gate-action@master
   #     timeout-minutes: 5
   #     env:
   #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   #       SONAR_HOST_URL: https://sonarcloud.io

  build-and-push:
    name: Build and Push Image
    needs: [gitleaks, semgrep, trivy, sonarqube]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/devops-demo-app
          tags: |
            type=sha,prefix=
            type=raw,value=latest
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  update-manifest:
    name: Update Kubernetes Manifest
    needs: [build-and-push]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update image tag in deployment
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          sed -i "s|image: .*/devops-demo-app:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/devops-demo-app:${SHORT_SHA}|" k8s/deployment.yaml
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git diff --staged --quiet || git commit -m "chore: update image tag to ${{ github.sha }}"
          git push origin HEAD:main
